export const SchoolList = [
    'Algonquin College',
    'Collège Boréal',
    'Cambrian College',
    'Canadore College',
    'Centennial College',
    'Conestoga College',
    'Confederation College',
    'Durham College',
    'Fanshawe College',
    'Fleming College',
    'George Brown College',
    'Georgian College',
    'Humber College',
    'La Cité collégiale',
    'Lambton College',
    'Loyalist College',
    'Mohawk College',
    'Niagara College',
    'Northern College',
    'St. Clair College',
    'St. Lawrence College',
    'Sault College',
    'Seneca College',
    'Sheridan College',
    'Algoma University',
    'Brescia University College',
    'Brock University',
    'Carleton University',
    'Dominican University College',
    'Royal Military College of Canada',
    'Huron University',
    'King’s University College',
    'Lakehead University',
    'McMaster University',
    'Nipissing University',
    'OCAD University',
    'Queen’s University',
    'Redeemer University College',
    'Ryerson University',
    'Jerome’s University',
    'Trent University',
    'University of Ottawa',
    'University of Sudbury',
    'Laurentian University',
    'Saint Paul University',
    'University of Guelph',
    'Ontario Tech University',
    'University of Michael’s College',
    'University of Toronto',
    'Trinity Western University',
    'University of Waterloo',
    'University of Windsor',
    'Wilfrid Laurier University',
    'York University',
    'University of Hearst',
]